version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: nest-backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      # NestJSがMySQLへ接続するための環境変数
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: password
      DB_NAME: mydb
    depends_on:
      - mysql
    command: >
      sh -c "npm run build && npm run start:prod"
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mysql_data:
